hyperparameters:
  batch_size: 64
  clip: 1
  d_ff: 1024
  d_model: 512
  dropout: 0.3
  embedding_dim: 128
  hidden_dim: 256
  learning_rate: 0.001
  max_length: 25
  num_epochs: 4
  num_heads: 4
  num_layers: 2
  vocab_size: 30524
model_params:
  dropout: 0.2
  model_name: bert-base-uncased
  out_features: 1024
train_test_split:
  random_state: 21
  test_size: 0.2
